In [5]:
import pandas as pd
df = pd.read_excel("sales_data.xlsx")

In [6]:
df

        Date Region  Product  Sales  Cost
0 2026-01-01    NSW   Laptop   1000   700
1 2026-01-02    VIC  Monitor    500   600
2 2026-01-03    NSW   Laptop   1500  1550
3 2026-01-04    QLD    Mouse    300   500
4 2026-01-05    VIC   Laptop   2000  2300

In [9]:
def totalSales(x):
  return x["Sales"].sum()

totalSales(df)

np.int64(5300)

In [10]:
def totalCal(x):
  return x.sum()

totalCal(df["Sales"])

np.int64(5300)

In [12]:
totalSales(df.groupby("Region"))

Region
NSW    2500
QLD     300
VIC    2500
Name: Sales, dtype: int64

In [13]:
def top_product(df):

    result = (
        df.groupby("Product")["Sales"]
          .sum()
          .sort_values(ascending=False)
    )

    return result.head(1)

top_product(df)

Product
Laptop    4500
Name: Sales, dtype: int64

In [15]:
def executive_summary(df):

    total_sales_value = df["Sales"].sum()

    total_cost_value = df["Cost"].sum()

    print("Executive Summary")
    print("----------------")
    print("Total Sales:", total_sales_value)
    print("Total Cost:", total_cost_value)

executive_summary(df)

Executive Summary
----------------
Total Sales: 5300
Total Cost: 5650

In [17]:
def average_sales(df):
  x = df["Sales"].mean()
  return x

average_sales(df)

np.float64(1060.0)

In [39]:
def highest_sale(df):
  x = df["Sales"].sort_values(ascending=False).head(1)
  return x

print(highest_sale(df))

df[df['Sales']==df['Sales'].max()]

4    2000
Name: Sales, dtype: int64

        Date Region Product  Sales  Cost
4 2026-01-05    VIC  Laptop   2000  2300

In [32]:
def top_region(df):
  x = df.groupby('Region')["Sales"].sum()
  return x.head(1)

top_region(df)

Region
NSW    2500
Name: Sales, dtype: int64